[workspace]
members = ["cargo:."]

[dist]
cargo-dist-version = "0.30.4"
ci = "github"
installers = ["shell", "powershell"]
targets = ["x86_64-unknown-linux-musl"]
pr-run-mode = "skip"
install-updater = false
